// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: org/jeecf/kong/rpc/protocol/serializer/RequestProto.proto

package org.jeecf.kong.rpc.protocol.serializer;

public final class RequestProto {
  private RequestProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.jeecf.kong.rpc.protocol.serializer.Request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     **
     * 全局通信id
     * </pre>
     *
     * <code>string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <pre>
     **
     * 全局通信id
     * </pre>
     *
     * <code>string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <pre>
     **
     * 当前通信id
     * </pre>
     *
     * <code>string clientSpan = 2;</code>
     */
    java.lang.String getClientSpan();
    /**
     * <pre>
     **
     * 当前通信id
     * </pre>
     *
     * <code>string clientSpan = 2;</code>
     */
    com.google.protobuf.ByteString
        getClientSpanBytes();

    /**
     * <pre>
     **
     * 客户端发送时自定义的id
     * </pre>
     *
     * <code>string clientId = 3;</code>
     */
    java.lang.String getClientId();
    /**
     * <pre>
     **
     * 客户端发送时自定义的id
     * </pre>
     *
     * <code>string clientId = 3;</code>
     */
    com.google.protobuf.ByteString
        getClientIdBytes();

    /**
     * <pre>
     **
     * 资源版本
     * </pre>
     *
     * <code>int32 version = 4;</code>
     */
    int getVersion();

    /**
     * <pre>
     **
     * 传输模式
     * </pre>
     *
     * <code>bytes transferMode = 5;</code>
     */
    com.google.protobuf.ByteString getTransferMode();

    /**
     * <pre>
     **
     * 资源路径
     * </pre>
     *
     * <code>string path = 6;</code>
     */
    java.lang.String getPath();
    /**
     * <pre>
     **
     * 资源路径
     * </pre>
     *
     * <code>string path = 6;</code>
     */
    com.google.protobuf.ByteString
        getPathBytes();

    /**
     * <pre>
     **
     * 参数
     * </pre>
     *
     * <code>string args = 7;</code>
     */
    java.lang.String getArgs();
    /**
     * <pre>
     **
     * 参数
     * </pre>
     *
     * <code>string args = 7;</code>
     */
    com.google.protobuf.ByteString
        getArgsBytes();

    /**
     * <pre>
     **
     * 通信时间
     * </pre>
     *
     * <code>sint64 time = 8;</code>
     */
    long getTime();
  }
  /**
   * <pre>
   **
   *  通信请求Request
   * </pre>
   *
   * Protobuf type {@code org.jeecf.kong.rpc.protocol.serializer.Request}
   */
  public  static final class Request extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.jeecf.kong.rpc.protocol.serializer.Request)
      RequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Request.newBuilder() to construct.
    private Request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Request() {
      id_ = "";
      clientSpan_ = "";
      clientId_ = "";
      version_ = 0;
      transferMode_ = com.google.protobuf.ByteString.EMPTY;
      path_ = "";
      args_ = "";
      time_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              clientSpan_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              clientId_ = s;
              break;
            }
            case 32: {

              version_ = input.readInt32();
              break;
            }
            case 42: {

              transferMode_ = input.readBytes();
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              path_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              args_ = s;
              break;
            }
            case 64: {

              time_ = input.readSInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.jeecf.kong.rpc.protocol.serializer.RequestProto.internal_static_org_jeecf_kong_rpc_protocol_serializer_Request_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.jeecf.kong.rpc.protocol.serializer.RequestProto.internal_static_org_jeecf_kong_rpc_protocol_serializer_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.jeecf.kong.rpc.protocol.serializer.RequestProto.Request.class, org.jeecf.kong.rpc.protocol.serializer.RequestProto.Request.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <pre>
     **
     * 全局通信id
     * </pre>
     *
     * <code>string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <pre>
     **
     * 全局通信id
     * </pre>
     *
     * <code>string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CLIENTSPAN_FIELD_NUMBER = 2;
    private volatile java.lang.Object clientSpan_;
    /**
     * <pre>
     **
     * 当前通信id
     * </pre>
     *
     * <code>string clientSpan = 2;</code>
     */
    public java.lang.String getClientSpan() {
      java.lang.Object ref = clientSpan_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clientSpan_ = s;
        return s;
      }
    }
    /**
     * <pre>
     **
     * 当前通信id
     * </pre>
     *
     * <code>string clientSpan = 2;</code>
     */
    public com.google.protobuf.ByteString
        getClientSpanBytes() {
      java.lang.Object ref = clientSpan_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientSpan_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CLIENTID_FIELD_NUMBER = 3;
    private volatile java.lang.Object clientId_;
    /**
     * <pre>
     **
     * 客户端发送时自定义的id
     * </pre>
     *
     * <code>string clientId = 3;</code>
     */
    public java.lang.String getClientId() {
      java.lang.Object ref = clientId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clientId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     **
     * 客户端发送时自定义的id
     * </pre>
     *
     * <code>string clientId = 3;</code>
     */
    public com.google.protobuf.ByteString
        getClientIdBytes() {
      java.lang.Object ref = clientId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VERSION_FIELD_NUMBER = 4;
    private int version_;
    /**
     * <pre>
     **
     * 资源版本
     * </pre>
     *
     * <code>int32 version = 4;</code>
     */
    public int getVersion() {
      return version_;
    }

    public static final int TRANSFERMODE_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString transferMode_;
    /**
     * <pre>
     **
     * 传输模式
     * </pre>
     *
     * <code>bytes transferMode = 5;</code>
     */
    public com.google.protobuf.ByteString getTransferMode() {
      return transferMode_;
    }

    public static final int PATH_FIELD_NUMBER = 6;
    private volatile java.lang.Object path_;
    /**
     * <pre>
     **
     * 资源路径
     * </pre>
     *
     * <code>string path = 6;</code>
     */
    public java.lang.String getPath() {
      java.lang.Object ref = path_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        path_ = s;
        return s;
      }
    }
    /**
     * <pre>
     **
     * 资源路径
     * </pre>
     *
     * <code>string path = 6;</code>
     */
    public com.google.protobuf.ByteString
        getPathBytes() {
      java.lang.Object ref = path_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        path_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ARGS_FIELD_NUMBER = 7;
    private volatile java.lang.Object args_;
    /**
     * <pre>
     **
     * 参数
     * </pre>
     *
     * <code>string args = 7;</code>
     */
    public java.lang.String getArgs() {
      java.lang.Object ref = args_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        args_ = s;
        return s;
      }
    }
    /**
     * <pre>
     **
     * 参数
     * </pre>
     *
     * <code>string args = 7;</code>
     */
    public com.google.protobuf.ByteString
        getArgsBytes() {
      java.lang.Object ref = args_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        args_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIME_FIELD_NUMBER = 8;
    private long time_;
    /**
     * <pre>
     **
     * 通信时间
     * </pre>
     *
     * <code>sint64 time = 8;</code>
     */
    public long getTime() {
      return time_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (!getClientSpanBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, clientSpan_);
      }
      if (!getClientIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, clientId_);
      }
      if (version_ != 0) {
        output.writeInt32(4, version_);
      }
      if (!transferMode_.isEmpty()) {
        output.writeBytes(5, transferMode_);
      }
      if (!getPathBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, path_);
      }
      if (!getArgsBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, args_);
      }
      if (time_ != 0L) {
        output.writeSInt64(8, time_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (!getClientSpanBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, clientSpan_);
      }
      if (!getClientIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, clientId_);
      }
      if (version_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, version_);
      }
      if (!transferMode_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, transferMode_);
      }
      if (!getPathBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, path_);
      }
      if (!getArgsBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, args_);
      }
      if (time_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt64Size(8, time_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.jeecf.kong.rpc.protocol.serializer.RequestProto.Request)) {
        return super.equals(obj);
      }
      org.jeecf.kong.rpc.protocol.serializer.RequestProto.Request other = (org.jeecf.kong.rpc.protocol.serializer.RequestProto.Request) obj;

      boolean result = true;
      result = result && getId()
          .equals(other.getId());
      result = result && getClientSpan()
          .equals(other.getClientSpan());
      result = result && getClientId()
          .equals(other.getClientId());
      result = result && (getVersion()
          == other.getVersion());
      result = result && getTransferMode()
          .equals(other.getTransferMode());
      result = result && getPath()
          .equals(other.getPath());
      result = result && getArgs()
          .equals(other.getArgs());
      result = result && (getTime()
          == other.getTime());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + CLIENTSPAN_FIELD_NUMBER;
      hash = (53 * hash) + getClientSpan().hashCode();
      hash = (37 * hash) + CLIENTID_FIELD_NUMBER;
      hash = (53 * hash) + getClientId().hashCode();
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion();
      hash = (37 * hash) + TRANSFERMODE_FIELD_NUMBER;
      hash = (53 * hash) + getTransferMode().hashCode();
      hash = (37 * hash) + PATH_FIELD_NUMBER;
      hash = (53 * hash) + getPath().hashCode();
      hash = (37 * hash) + ARGS_FIELD_NUMBER;
      hash = (53 * hash) + getArgs().hashCode();
      hash = (37 * hash) + TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTime());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.jeecf.kong.rpc.protocol.serializer.RequestProto.Request parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.jeecf.kong.rpc.protocol.serializer.RequestProto.Request parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.jeecf.kong.rpc.protocol.serializer.RequestProto.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.jeecf.kong.rpc.protocol.serializer.RequestProto.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.jeecf.kong.rpc.protocol.serializer.RequestProto.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.jeecf.kong.rpc.protocol.serializer.RequestProto.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.jeecf.kong.rpc.protocol.serializer.RequestProto.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.jeecf.kong.rpc.protocol.serializer.RequestProto.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.jeecf.kong.rpc.protocol.serializer.RequestProto.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.jeecf.kong.rpc.protocol.serializer.RequestProto.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.jeecf.kong.rpc.protocol.serializer.RequestProto.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.jeecf.kong.rpc.protocol.serializer.RequestProto.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.jeecf.kong.rpc.protocol.serializer.RequestProto.Request prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     **
     *  通信请求Request
     * </pre>
     *
     * Protobuf type {@code org.jeecf.kong.rpc.protocol.serializer.Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.jeecf.kong.rpc.protocol.serializer.Request)
        org.jeecf.kong.rpc.protocol.serializer.RequestProto.RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.jeecf.kong.rpc.protocol.serializer.RequestProto.internal_static_org_jeecf_kong_rpc_protocol_serializer_Request_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.jeecf.kong.rpc.protocol.serializer.RequestProto.internal_static_org_jeecf_kong_rpc_protocol_serializer_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.jeecf.kong.rpc.protocol.serializer.RequestProto.Request.class, org.jeecf.kong.rpc.protocol.serializer.RequestProto.Request.Builder.class);
      }

      // Construct using org.jeecf.kong.rpc.protocol.serializer.RequestProto.Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = "";

        clientSpan_ = "";

        clientId_ = "";

        version_ = 0;

        transferMode_ = com.google.protobuf.ByteString.EMPTY;

        path_ = "";

        args_ = "";

        time_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.jeecf.kong.rpc.protocol.serializer.RequestProto.internal_static_org_jeecf_kong_rpc_protocol_serializer_Request_descriptor;
      }

      public org.jeecf.kong.rpc.protocol.serializer.RequestProto.Request getDefaultInstanceForType() {
        return org.jeecf.kong.rpc.protocol.serializer.RequestProto.Request.getDefaultInstance();
      }

      public org.jeecf.kong.rpc.protocol.serializer.RequestProto.Request build() {
        org.jeecf.kong.rpc.protocol.serializer.RequestProto.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.jeecf.kong.rpc.protocol.serializer.RequestProto.Request buildPartial() {
        org.jeecf.kong.rpc.protocol.serializer.RequestProto.Request result = new org.jeecf.kong.rpc.protocol.serializer.RequestProto.Request(this);
        result.id_ = id_;
        result.clientSpan_ = clientSpan_;
        result.clientId_ = clientId_;
        result.version_ = version_;
        result.transferMode_ = transferMode_;
        result.path_ = path_;
        result.args_ = args_;
        result.time_ = time_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.jeecf.kong.rpc.protocol.serializer.RequestProto.Request) {
          return mergeFrom((org.jeecf.kong.rpc.protocol.serializer.RequestProto.Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.jeecf.kong.rpc.protocol.serializer.RequestProto.Request other) {
        if (other == org.jeecf.kong.rpc.protocol.serializer.RequestProto.Request.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (!other.getClientSpan().isEmpty()) {
          clientSpan_ = other.clientSpan_;
          onChanged();
        }
        if (!other.getClientId().isEmpty()) {
          clientId_ = other.clientId_;
          onChanged();
        }
        if (other.getVersion() != 0) {
          setVersion(other.getVersion());
        }
        if (other.getTransferMode() != com.google.protobuf.ByteString.EMPTY) {
          setTransferMode(other.getTransferMode());
        }
        if (!other.getPath().isEmpty()) {
          path_ = other.path_;
          onChanged();
        }
        if (!other.getArgs().isEmpty()) {
          args_ = other.args_;
          onChanged();
        }
        if (other.getTime() != 0L) {
          setTime(other.getTime());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.jeecf.kong.rpc.protocol.serializer.RequestProto.Request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.jeecf.kong.rpc.protocol.serializer.RequestProto.Request) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <pre>
       **
       * 全局通信id
       * </pre>
       *
       * <code>string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       **
       * 全局通信id
       * </pre>
       *
       * <code>string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       **
       * 全局通信id
       * </pre>
       *
       * <code>string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 全局通信id
       * </pre>
       *
       * <code>string id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 全局通信id
       * </pre>
       *
       * <code>string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object clientSpan_ = "";
      /**
       * <pre>
       **
       * 当前通信id
       * </pre>
       *
       * <code>string clientSpan = 2;</code>
       */
      public java.lang.String getClientSpan() {
        java.lang.Object ref = clientSpan_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          clientSpan_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       **
       * 当前通信id
       * </pre>
       *
       * <code>string clientSpan = 2;</code>
       */
      public com.google.protobuf.ByteString
          getClientSpanBytes() {
        java.lang.Object ref = clientSpan_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          clientSpan_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       **
       * 当前通信id
       * </pre>
       *
       * <code>string clientSpan = 2;</code>
       */
      public Builder setClientSpan(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        clientSpan_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 当前通信id
       * </pre>
       *
       * <code>string clientSpan = 2;</code>
       */
      public Builder clearClientSpan() {
        
        clientSpan_ = getDefaultInstance().getClientSpan();
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 当前通信id
       * </pre>
       *
       * <code>string clientSpan = 2;</code>
       */
      public Builder setClientSpanBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        clientSpan_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object clientId_ = "";
      /**
       * <pre>
       **
       * 客户端发送时自定义的id
       * </pre>
       *
       * <code>string clientId = 3;</code>
       */
      public java.lang.String getClientId() {
        java.lang.Object ref = clientId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          clientId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       **
       * 客户端发送时自定义的id
       * </pre>
       *
       * <code>string clientId = 3;</code>
       */
      public com.google.protobuf.ByteString
          getClientIdBytes() {
        java.lang.Object ref = clientId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          clientId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       **
       * 客户端发送时自定义的id
       * </pre>
       *
       * <code>string clientId = 3;</code>
       */
      public Builder setClientId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        clientId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 客户端发送时自定义的id
       * </pre>
       *
       * <code>string clientId = 3;</code>
       */
      public Builder clearClientId() {
        
        clientId_ = getDefaultInstance().getClientId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 客户端发送时自定义的id
       * </pre>
       *
       * <code>string clientId = 3;</code>
       */
      public Builder setClientIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        clientId_ = value;
        onChanged();
        return this;
      }

      private int version_ ;
      /**
       * <pre>
       **
       * 资源版本
       * </pre>
       *
       * <code>int32 version = 4;</code>
       */
      public int getVersion() {
        return version_;
      }
      /**
       * <pre>
       **
       * 资源版本
       * </pre>
       *
       * <code>int32 version = 4;</code>
       */
      public Builder setVersion(int value) {
        
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 资源版本
       * </pre>
       *
       * <code>int32 version = 4;</code>
       */
      public Builder clearVersion() {
        
        version_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString transferMode_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       **
       * 传输模式
       * </pre>
       *
       * <code>bytes transferMode = 5;</code>
       */
      public com.google.protobuf.ByteString getTransferMode() {
        return transferMode_;
      }
      /**
       * <pre>
       **
       * 传输模式
       * </pre>
       *
       * <code>bytes transferMode = 5;</code>
       */
      public Builder setTransferMode(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        transferMode_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 传输模式
       * </pre>
       *
       * <code>bytes transferMode = 5;</code>
       */
      public Builder clearTransferMode() {
        
        transferMode_ = getDefaultInstance().getTransferMode();
        onChanged();
        return this;
      }

      private java.lang.Object path_ = "";
      /**
       * <pre>
       **
       * 资源路径
       * </pre>
       *
       * <code>string path = 6;</code>
       */
      public java.lang.String getPath() {
        java.lang.Object ref = path_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          path_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       **
       * 资源路径
       * </pre>
       *
       * <code>string path = 6;</code>
       */
      public com.google.protobuf.ByteString
          getPathBytes() {
        java.lang.Object ref = path_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          path_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       **
       * 资源路径
       * </pre>
       *
       * <code>string path = 6;</code>
       */
      public Builder setPath(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        path_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 资源路径
       * </pre>
       *
       * <code>string path = 6;</code>
       */
      public Builder clearPath() {
        
        path_ = getDefaultInstance().getPath();
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 资源路径
       * </pre>
       *
       * <code>string path = 6;</code>
       */
      public Builder setPathBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        path_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object args_ = "";
      /**
       * <pre>
       **
       * 参数
       * </pre>
       *
       * <code>string args = 7;</code>
       */
      public java.lang.String getArgs() {
        java.lang.Object ref = args_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          args_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       **
       * 参数
       * </pre>
       *
       * <code>string args = 7;</code>
       */
      public com.google.protobuf.ByteString
          getArgsBytes() {
        java.lang.Object ref = args_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          args_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       **
       * 参数
       * </pre>
       *
       * <code>string args = 7;</code>
       */
      public Builder setArgs(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        args_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 参数
       * </pre>
       *
       * <code>string args = 7;</code>
       */
      public Builder clearArgs() {
        
        args_ = getDefaultInstance().getArgs();
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 参数
       * </pre>
       *
       * <code>string args = 7;</code>
       */
      public Builder setArgsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        args_ = value;
        onChanged();
        return this;
      }

      private long time_ ;
      /**
       * <pre>
       **
       * 通信时间
       * </pre>
       *
       * <code>sint64 time = 8;</code>
       */
      public long getTime() {
        return time_;
      }
      /**
       * <pre>
       **
       * 通信时间
       * </pre>
       *
       * <code>sint64 time = 8;</code>
       */
      public Builder setTime(long value) {
        
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 通信时间
       * </pre>
       *
       * <code>sint64 time = 8;</code>
       */
      public Builder clearTime() {
        
        time_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.jeecf.kong.rpc.protocol.serializer.Request)
    }

    // @@protoc_insertion_point(class_scope:org.jeecf.kong.rpc.protocol.serializer.Request)
    private static final org.jeecf.kong.rpc.protocol.serializer.RequestProto.Request DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.jeecf.kong.rpc.protocol.serializer.RequestProto.Request();
    }

    public static org.jeecf.kong.rpc.protocol.serializer.RequestProto.Request getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Request>
        PARSER = new com.google.protobuf.AbstractParser<Request>() {
      public Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Request(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Request> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Request> getParserForType() {
      return PARSER;
    }

    public org.jeecf.kong.rpc.protocol.serializer.RequestProto.Request getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_jeecf_kong_rpc_protocol_serializer_Request_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_jeecf_kong_rpc_protocol_serializer_Request_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n9org/jeecf/kong/rpc/protocol/serializer" +
      "/RequestProto.proto\022&org.jeecf.kong.rpc." +
      "protocol.serializer\"\214\001\n\007Request\022\n\n\002id\030\001 " +
      "\001(\t\022\022\n\nclientSpan\030\002 \001(\t\022\020\n\010clientId\030\003 \001(" +
      "\t\022\017\n\007version\030\004 \001(\005\022\024\n\014transferMode\030\005 \001(\014" +
      "\022\014\n\004path\030\006 \001(\t\022\014\n\004args\030\007 \001(\t\022\014\n\004time\030\010 \001" +
      "(\022B6\n&org.jeecf.kong.rpc.protocol.serial" +
      "izerB\014RequestProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_org_jeecf_kong_rpc_protocol_serializer_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_jeecf_kong_rpc_protocol_serializer_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_jeecf_kong_rpc_protocol_serializer_Request_descriptor,
        new java.lang.String[] { "Id", "ClientSpan", "ClientId", "Version", "TransferMode", "Path", "Args", "Time", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
