// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: org/jeecf/kong/rpc/protocol/serializer/ResponseProto.proto

package org.jeecf.kong.rpc.protocol.serializer;

public final class ResponseProto {
  private ResponseProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.jeecf.kong.rpc.protocol.serializer.Response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     **
     * 调用方id
     * </pre>
     *
     * <code>string clientSpan = 1;</code>
     */
    java.lang.String getClientSpan();
    /**
     * <pre>
     **
     * 调用方id
     * </pre>
     *
     * <code>string clientSpan = 1;</code>
     */
    com.google.protobuf.ByteString
        getClientSpanBytes();

    /**
     * <pre>
     **
     * 当前id
     * </pre>
     *
     * <code>string serverSpan = 2;</code>
     */
    java.lang.String getServerSpan();
    /**
     * <pre>
     **
     * 当前id
     * </pre>
     *
     * <code>string serverSpan = 2;</code>
     */
    com.google.protobuf.ByteString
        getServerSpanBytes();

    /**
     * <pre>
     **
     * 响应码
     * </pre>
     *
     * <code>int32 code = 3;</code>
     */
    int getCode();

    /**
     * <pre>
     **
     * 响应消息
     * </pre>
     *
     * <code>string message = 4;</code>
     */
    java.lang.String getMessage();
    /**
     * <pre>
     **
     * 响应消息
     * </pre>
     *
     * <code>string message = 4;</code>
     */
    com.google.protobuf.ByteString
        getMessageBytes();

    /**
     * <pre>
     **
     * 响应数据
     * </pre>
     *
     * <code>string data = 5;</code>
     */
    java.lang.String getData();
    /**
     * <pre>
     **
     * 响应数据
     * </pre>
     *
     * <code>string data = 5;</code>
     */
    com.google.protobuf.ByteString
        getDataBytes();

    /**
     * <pre>
     **
     * 通信时间
     * </pre>
     *
     * <code>sint64 sr = 6;</code>
     */
    long getSr();

    /**
     * <pre>
     **
     * 通信时间
     * </pre>
     *
     * <code>sint64 ss = 7;</code>
     */
    long getSs();
  }
  /**
   * <pre>
   **
   *  通信响应 ResponseeProto
   * </pre>
   *
   * Protobuf type {@code org.jeecf.kong.rpc.protocol.serializer.Response}
   */
  public  static final class Response extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.jeecf.kong.rpc.protocol.serializer.Response)
      ResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Response.newBuilder() to construct.
    private Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Response() {
      clientSpan_ = "";
      serverSpan_ = "";
      code_ = 0;
      message_ = "";
      data_ = "";
      sr_ = 0L;
      ss_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              clientSpan_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              serverSpan_ = s;
              break;
            }
            case 24: {

              code_ = input.readInt32();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              message_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              data_ = s;
              break;
            }
            case 48: {

              sr_ = input.readSInt64();
              break;
            }
            case 56: {

              ss_ = input.readSInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.jeecf.kong.rpc.protocol.serializer.ResponseProto.internal_static_org_jeecf_kong_rpc_protocol_serializer_Response_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.jeecf.kong.rpc.protocol.serializer.ResponseProto.internal_static_org_jeecf_kong_rpc_protocol_serializer_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.jeecf.kong.rpc.protocol.serializer.ResponseProto.Response.class, org.jeecf.kong.rpc.protocol.serializer.ResponseProto.Response.Builder.class);
    }

    public static final int CLIENTSPAN_FIELD_NUMBER = 1;
    private volatile java.lang.Object clientSpan_;
    /**
     * <pre>
     **
     * 调用方id
     * </pre>
     *
     * <code>string clientSpan = 1;</code>
     */
    public java.lang.String getClientSpan() {
      java.lang.Object ref = clientSpan_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clientSpan_ = s;
        return s;
      }
    }
    /**
     * <pre>
     **
     * 调用方id
     * </pre>
     *
     * <code>string clientSpan = 1;</code>
     */
    public com.google.protobuf.ByteString
        getClientSpanBytes() {
      java.lang.Object ref = clientSpan_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientSpan_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SERVERSPAN_FIELD_NUMBER = 2;
    private volatile java.lang.Object serverSpan_;
    /**
     * <pre>
     **
     * 当前id
     * </pre>
     *
     * <code>string serverSpan = 2;</code>
     */
    public java.lang.String getServerSpan() {
      java.lang.Object ref = serverSpan_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        serverSpan_ = s;
        return s;
      }
    }
    /**
     * <pre>
     **
     * 当前id
     * </pre>
     *
     * <code>string serverSpan = 2;</code>
     */
    public com.google.protobuf.ByteString
        getServerSpanBytes() {
      java.lang.Object ref = serverSpan_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serverSpan_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CODE_FIELD_NUMBER = 3;
    private int code_;
    /**
     * <pre>
     **
     * 响应码
     * </pre>
     *
     * <code>int32 code = 3;</code>
     */
    public int getCode() {
      return code_;
    }

    public static final int MESSAGE_FIELD_NUMBER = 4;
    private volatile java.lang.Object message_;
    /**
     * <pre>
     **
     * 响应消息
     * </pre>
     *
     * <code>string message = 4;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <pre>
     **
     * 响应消息
     * </pre>
     *
     * <code>string message = 4;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATA_FIELD_NUMBER = 5;
    private volatile java.lang.Object data_;
    /**
     * <pre>
     **
     * 响应数据
     * </pre>
     *
     * <code>string data = 5;</code>
     */
    public java.lang.String getData() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        data_ = s;
        return s;
      }
    }
    /**
     * <pre>
     **
     * 响应数据
     * </pre>
     *
     * <code>string data = 5;</code>
     */
    public com.google.protobuf.ByteString
        getDataBytes() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        data_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SR_FIELD_NUMBER = 6;
    private long sr_;
    /**
     * <pre>
     **
     * 通信时间
     * </pre>
     *
     * <code>sint64 sr = 6;</code>
     */
    public long getSr() {
      return sr_;
    }

    public static final int SS_FIELD_NUMBER = 7;
    private long ss_;
    /**
     * <pre>
     **
     * 通信时间
     * </pre>
     *
     * <code>sint64 ss = 7;</code>
     */
    public long getSs() {
      return ss_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getClientSpanBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, clientSpan_);
      }
      if (!getServerSpanBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, serverSpan_);
      }
      if (code_ != 0) {
        output.writeInt32(3, code_);
      }
      if (!getMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, message_);
      }
      if (!getDataBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, data_);
      }
      if (sr_ != 0L) {
        output.writeSInt64(6, sr_);
      }
      if (ss_ != 0L) {
        output.writeSInt64(7, ss_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getClientSpanBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, clientSpan_);
      }
      if (!getServerSpanBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, serverSpan_);
      }
      if (code_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, code_);
      }
      if (!getMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, message_);
      }
      if (!getDataBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, data_);
      }
      if (sr_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt64Size(6, sr_);
      }
      if (ss_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt64Size(7, ss_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.jeecf.kong.rpc.protocol.serializer.ResponseProto.Response)) {
        return super.equals(obj);
      }
      org.jeecf.kong.rpc.protocol.serializer.ResponseProto.Response other = (org.jeecf.kong.rpc.protocol.serializer.ResponseProto.Response) obj;

      boolean result = true;
      result = result && getClientSpan()
          .equals(other.getClientSpan());
      result = result && getServerSpan()
          .equals(other.getServerSpan());
      result = result && (getCode()
          == other.getCode());
      result = result && getMessage()
          .equals(other.getMessage());
      result = result && getData()
          .equals(other.getData());
      result = result && (getSr()
          == other.getSr());
      result = result && (getSs()
          == other.getSs());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CLIENTSPAN_FIELD_NUMBER;
      hash = (53 * hash) + getClientSpan().hashCode();
      hash = (37 * hash) + SERVERSPAN_FIELD_NUMBER;
      hash = (53 * hash) + getServerSpan().hashCode();
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + getCode();
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (37 * hash) + SR_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSr());
      hash = (37 * hash) + SS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSs());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.jeecf.kong.rpc.protocol.serializer.ResponseProto.Response parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.jeecf.kong.rpc.protocol.serializer.ResponseProto.Response parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.jeecf.kong.rpc.protocol.serializer.ResponseProto.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.jeecf.kong.rpc.protocol.serializer.ResponseProto.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.jeecf.kong.rpc.protocol.serializer.ResponseProto.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.jeecf.kong.rpc.protocol.serializer.ResponseProto.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.jeecf.kong.rpc.protocol.serializer.ResponseProto.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.jeecf.kong.rpc.protocol.serializer.ResponseProto.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.jeecf.kong.rpc.protocol.serializer.ResponseProto.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.jeecf.kong.rpc.protocol.serializer.ResponseProto.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.jeecf.kong.rpc.protocol.serializer.ResponseProto.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.jeecf.kong.rpc.protocol.serializer.ResponseProto.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.jeecf.kong.rpc.protocol.serializer.ResponseProto.Response prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     **
     *  通信响应 ResponseeProto
     * </pre>
     *
     * Protobuf type {@code org.jeecf.kong.rpc.protocol.serializer.Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.jeecf.kong.rpc.protocol.serializer.Response)
        org.jeecf.kong.rpc.protocol.serializer.ResponseProto.ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.jeecf.kong.rpc.protocol.serializer.ResponseProto.internal_static_org_jeecf_kong_rpc_protocol_serializer_Response_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.jeecf.kong.rpc.protocol.serializer.ResponseProto.internal_static_org_jeecf_kong_rpc_protocol_serializer_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.jeecf.kong.rpc.protocol.serializer.ResponseProto.Response.class, org.jeecf.kong.rpc.protocol.serializer.ResponseProto.Response.Builder.class);
      }

      // Construct using org.jeecf.kong.rpc.protocol.serializer.ResponseProto.Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        clientSpan_ = "";

        serverSpan_ = "";

        code_ = 0;

        message_ = "";

        data_ = "";

        sr_ = 0L;

        ss_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.jeecf.kong.rpc.protocol.serializer.ResponseProto.internal_static_org_jeecf_kong_rpc_protocol_serializer_Response_descriptor;
      }

      public org.jeecf.kong.rpc.protocol.serializer.ResponseProto.Response getDefaultInstanceForType() {
        return org.jeecf.kong.rpc.protocol.serializer.ResponseProto.Response.getDefaultInstance();
      }

      public org.jeecf.kong.rpc.protocol.serializer.ResponseProto.Response build() {
        org.jeecf.kong.rpc.protocol.serializer.ResponseProto.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.jeecf.kong.rpc.protocol.serializer.ResponseProto.Response buildPartial() {
        org.jeecf.kong.rpc.protocol.serializer.ResponseProto.Response result = new org.jeecf.kong.rpc.protocol.serializer.ResponseProto.Response(this);
        result.clientSpan_ = clientSpan_;
        result.serverSpan_ = serverSpan_;
        result.code_ = code_;
        result.message_ = message_;
        result.data_ = data_;
        result.sr_ = sr_;
        result.ss_ = ss_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.jeecf.kong.rpc.protocol.serializer.ResponseProto.Response) {
          return mergeFrom((org.jeecf.kong.rpc.protocol.serializer.ResponseProto.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.jeecf.kong.rpc.protocol.serializer.ResponseProto.Response other) {
        if (other == org.jeecf.kong.rpc.protocol.serializer.ResponseProto.Response.getDefaultInstance()) return this;
        if (!other.getClientSpan().isEmpty()) {
          clientSpan_ = other.clientSpan_;
          onChanged();
        }
        if (!other.getServerSpan().isEmpty()) {
          serverSpan_ = other.serverSpan_;
          onChanged();
        }
        if (other.getCode() != 0) {
          setCode(other.getCode());
        }
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          onChanged();
        }
        if (!other.getData().isEmpty()) {
          data_ = other.data_;
          onChanged();
        }
        if (other.getSr() != 0L) {
          setSr(other.getSr());
        }
        if (other.getSs() != 0L) {
          setSs(other.getSs());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.jeecf.kong.rpc.protocol.serializer.ResponseProto.Response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.jeecf.kong.rpc.protocol.serializer.ResponseProto.Response) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object clientSpan_ = "";
      /**
       * <pre>
       **
       * 调用方id
       * </pre>
       *
       * <code>string clientSpan = 1;</code>
       */
      public java.lang.String getClientSpan() {
        java.lang.Object ref = clientSpan_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          clientSpan_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       **
       * 调用方id
       * </pre>
       *
       * <code>string clientSpan = 1;</code>
       */
      public com.google.protobuf.ByteString
          getClientSpanBytes() {
        java.lang.Object ref = clientSpan_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          clientSpan_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       **
       * 调用方id
       * </pre>
       *
       * <code>string clientSpan = 1;</code>
       */
      public Builder setClientSpan(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        clientSpan_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 调用方id
       * </pre>
       *
       * <code>string clientSpan = 1;</code>
       */
      public Builder clearClientSpan() {
        
        clientSpan_ = getDefaultInstance().getClientSpan();
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 调用方id
       * </pre>
       *
       * <code>string clientSpan = 1;</code>
       */
      public Builder setClientSpanBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        clientSpan_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object serverSpan_ = "";
      /**
       * <pre>
       **
       * 当前id
       * </pre>
       *
       * <code>string serverSpan = 2;</code>
       */
      public java.lang.String getServerSpan() {
        java.lang.Object ref = serverSpan_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          serverSpan_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       **
       * 当前id
       * </pre>
       *
       * <code>string serverSpan = 2;</code>
       */
      public com.google.protobuf.ByteString
          getServerSpanBytes() {
        java.lang.Object ref = serverSpan_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          serverSpan_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       **
       * 当前id
       * </pre>
       *
       * <code>string serverSpan = 2;</code>
       */
      public Builder setServerSpan(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        serverSpan_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 当前id
       * </pre>
       *
       * <code>string serverSpan = 2;</code>
       */
      public Builder clearServerSpan() {
        
        serverSpan_ = getDefaultInstance().getServerSpan();
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 当前id
       * </pre>
       *
       * <code>string serverSpan = 2;</code>
       */
      public Builder setServerSpanBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        serverSpan_ = value;
        onChanged();
        return this;
      }

      private int code_ ;
      /**
       * <pre>
       **
       * 响应码
       * </pre>
       *
       * <code>int32 code = 3;</code>
       */
      public int getCode() {
        return code_;
      }
      /**
       * <pre>
       **
       * 响应码
       * </pre>
       *
       * <code>int32 code = 3;</code>
       */
      public Builder setCode(int value) {
        
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 响应码
       * </pre>
       *
       * <code>int32 code = 3;</code>
       */
      public Builder clearCode() {
        
        code_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <pre>
       **
       * 响应消息
       * </pre>
       *
       * <code>string message = 4;</code>
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       **
       * 响应消息
       * </pre>
       *
       * <code>string message = 4;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       **
       * 响应消息
       * </pre>
       *
       * <code>string message = 4;</code>
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 响应消息
       * </pre>
       *
       * <code>string message = 4;</code>
       */
      public Builder clearMessage() {
        
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 响应消息
       * </pre>
       *
       * <code>string message = 4;</code>
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        message_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object data_ = "";
      /**
       * <pre>
       **
       * 响应数据
       * </pre>
       *
       * <code>string data = 5;</code>
       */
      public java.lang.String getData() {
        java.lang.Object ref = data_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          data_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       **
       * 响应数据
       * </pre>
       *
       * <code>string data = 5;</code>
       */
      public com.google.protobuf.ByteString
          getDataBytes() {
        java.lang.Object ref = data_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          data_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       **
       * 响应数据
       * </pre>
       *
       * <code>string data = 5;</code>
       */
      public Builder setData(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 响应数据
       * </pre>
       *
       * <code>string data = 5;</code>
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 响应数据
       * </pre>
       *
       * <code>string data = 5;</code>
       */
      public Builder setDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        data_ = value;
        onChanged();
        return this;
      }

      private long sr_ ;
      /**
       * <pre>
       **
       * 通信时间
       * </pre>
       *
       * <code>sint64 sr = 6;</code>
       */
      public long getSr() {
        return sr_;
      }
      /**
       * <pre>
       **
       * 通信时间
       * </pre>
       *
       * <code>sint64 sr = 6;</code>
       */
      public Builder setSr(long value) {
        
        sr_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 通信时间
       * </pre>
       *
       * <code>sint64 sr = 6;</code>
       */
      public Builder clearSr() {
        
        sr_ = 0L;
        onChanged();
        return this;
      }

      private long ss_ ;
      /**
       * <pre>
       **
       * 通信时间
       * </pre>
       *
       * <code>sint64 ss = 7;</code>
       */
      public long getSs() {
        return ss_;
      }
      /**
       * <pre>
       **
       * 通信时间
       * </pre>
       *
       * <code>sint64 ss = 7;</code>
       */
      public Builder setSs(long value) {
        
        ss_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 通信时间
       * </pre>
       *
       * <code>sint64 ss = 7;</code>
       */
      public Builder clearSs() {
        
        ss_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.jeecf.kong.rpc.protocol.serializer.Response)
    }

    // @@protoc_insertion_point(class_scope:org.jeecf.kong.rpc.protocol.serializer.Response)
    private static final org.jeecf.kong.rpc.protocol.serializer.ResponseProto.Response DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.jeecf.kong.rpc.protocol.serializer.ResponseProto.Response();
    }

    public static org.jeecf.kong.rpc.protocol.serializer.ResponseProto.Response getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Response>
        PARSER = new com.google.protobuf.AbstractParser<Response>() {
      public Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Response(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Response> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Response> getParserForType() {
      return PARSER;
    }

    public org.jeecf.kong.rpc.protocol.serializer.ResponseProto.Response getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_jeecf_kong_rpc_protocol_serializer_Response_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_jeecf_kong_rpc_protocol_serializer_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n:org/jeecf/kong/rpc/protocol/serializer" +
      "/ResponseProto.proto\022&org.jeecf.kong.rpc" +
      ".protocol.serializer\"w\n\010Response\022\022\n\nclie" +
      "ntSpan\030\001 \001(\t\022\022\n\nserverSpan\030\002 \001(\t\022\014\n\004code" +
      "\030\003 \001(\005\022\017\n\007message\030\004 \001(\t\022\014\n\004data\030\005 \001(\t\022\n\n" +
      "\002sr\030\006 \001(\022\022\n\n\002ss\030\007 \001(\022B7\n&org.jeecf.kong." +
      "rpc.protocol.serializerB\rResponseProtob\006" +
      "proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_org_jeecf_kong_rpc_protocol_serializer_Response_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_jeecf_kong_rpc_protocol_serializer_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_jeecf_kong_rpc_protocol_serializer_Response_descriptor,
        new java.lang.String[] { "ClientSpan", "ServerSpan", "Code", "Message", "Data", "Sr", "Ss", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
